services:

  postgres:
    image: postgres:16
    container_name: fulfillx-postgres
    environment:
      POSTGRES_USER: fulfillx
      POSTGRES_PASSWORD: fulfillx123
      POSTGRES_DB: fulfillx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: fulfillx-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fulfillx-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: fulfillx
      RABBITMQ_DEFAULT_PASS: fulfillx123
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: