package com.fulfillx.auth.enums;

public enum Role {
    ADMIN,
    SELLER,
    WAREHOUSE_MANAGER,
    INBOUND_OPERATOR,
    PICKER_PACKER,
    INVENTORY_AUDITOR,
    VENDOR,
    CATALOGUE_MANAGER,
    FINANCE_MANAGER,
    SUPPORT_AGENT,
    RETURNS_AGENT
}